export const FETCH_COLLECTIONS_START : string = 'UPDATE_COLLECTIONS';
export const FETCH_COLLECTIONS_SUCCESS : string = 'FETCH_COLLECTIONS_SUCCESS';
export const FETCH_COLLECTIONS_FAILURE : string = 'FETCH_COLLECTIONS_FAILURE';


